/**
 * Mattermost permission constants and role definitions
 * Following official Mattermost permission system patterns
 */
export const Permissions = {
  // System scope permissions
  MANAGE_SYSTEM: 'manage_system',
  CREATE_TEAM: 'create_team',
  LIST_USERS_WITHOUT_TEAM: 'list_users_without_team',
  MANAGE_OAUTH: 'manage_oauth',
  MANAGE_SYSTEM_WIDE_OAUTH: 'manage_system_wide_oauth',
  CREATE_USER_ACCESS_TOKEN: 'create_user_access_token',
  READ_USER_ACCESS_TOKEN: 'read_user_access_token',
  REVOKE_USER_ACCESS_TOKEN: 'revoke_user_access_token',
  MANAGE_JOBS: 'manage_jobs',
  INVITE_GUEST: 'invite_guest',
  PROMOTE_GUEST: 'promote_guest',
  DEMOTE_TO_GUEST: 'demote_to_guest',
  MANAGE_REMOTE_CLUSTERS: 'manage_remote_clusters',
  
  // Team scope permissions
  INVITE_USER: 'invite_user',
  ADD_USER_TO_TEAM: 'add_user_to_team',
  REMOVE_USER_FROM_TEAM: 'remove_user_from_team',
  MANAGE_TEAM: 'manage_team',
  IMPORT_TEAM: 'import_team',
  VIEW_TEAM: 'view_team',
  CREATE_PUBLIC_CHANNEL: 'create_public_channel',
  CREATE_PRIVATE_CHANNEL: 'create_private_channel',
  JOIN_PUBLIC_CHANNELS: 'join_public_channels',
  MANAGE_INCOMING_WEBHOOKS: 'manage_incoming_webhooks',
  MANAGE_OUTGOING_WEBHOOKS: 'manage_outgoing_webhooks',
  CREATE_BOT: 'create_bot',
  
  // Channel scope permissions
  READ_CHANNEL: 'read_channel',
  CREATE_POST: 'create_post',
  EDIT_POST: 'edit_post',
  DELETE_POST: 'delete_post',
  MANAGE_PUBLIC_CHANNEL_PROPERTIES: 'manage_public_channel_properties',
  MANAGE_PRIVATE_CHANNEL_PROPERTIES: 'manage_private_channel_properties',
  MANAGE_PUBLIC_CHANNEL_MEMBERS: 'manage_public_channel_members',
  MANAGE_PRIVATE_CHANNEL_MEMBERS: 'manage_private_channel_members',
  ADD_REACTION: 'add_reaction',
  REMOVE_REACTION: 'remove_reaction',
  UPLOAD_FILE: 'upload_file',
  ADD_BOOKMARK_PUBLIC_CHANNEL: 'add_bookmark_public_channel',
  EDIT_BOOKMARK_PUBLIC_CHANNEL: 'edit_bookmark_public_channel',
} as const;

// Role definitions following Mattermost pattern
export const SystemRoles = {
  SYSTEM_ADMIN: 'system_admin',
  SYSTEM_USER: 'system_user',
} as const;

export const TeamRoles = {
  TEAM_ADMIN: 'team_admin',
  TEAM_USER: 'team_user',
} as const;

export const ChannelRoles = {
  CHANNEL_ADMIN: 'channel_admin',
  CHANNEL_USER: 'channel_user',
  CHANNEL_GUEST: 'channel_guest',
} as const;

// Permission mappings for roles - following Mattermost logic
export const RolePermissions = {
  [SystemRoles.SYSTEM_ADMIN]: [
    // System admin has all permissions
    Permissions.MANAGE_SYSTEM,
    Permissions.CREATE_TEAM,
    Permissions.LIST_USERS_WITHOUT_TEAM,
    Permissions.MANAGE_OAUTH,
    Permissions.MANAGE_SYSTEM_WIDE_OAUTH,
    Permissions.CREATE_USER_ACCESS_TOKEN,
    Permissions.READ_USER_ACCESS_TOKEN,
    Permissions.REVOKE_USER_ACCESS_TOKEN,
    Permissions.MANAGE_JOBS,
    Permissions.INVITE_GUEST,
    Permissions.PROMOTE_GUEST,
    Permissions.DEMOTE_TO_GUEST,
    Permissions.MANAGE_REMOTE_CLUSTERS,
    Permissions.INVITE_USER,
    Permissions.ADD_USER_TO_TEAM,
    Permissions.REMOVE_USER_FROM_TEAM,
    Permissions.MANAGE_TEAM,
    Permissions.IMPORT_TEAM,
    Permissions.VIEW_TEAM,
    Permissions.CREATE_PUBLIC_CHANNEL,
    Permissions.CREATE_PRIVATE_CHANNEL,
    Permissions.JOIN_PUBLIC_CHANNELS,
    Permissions.MANAGE_INCOMING_WEBHOOKS,
    Permissions.MANAGE_OUTGOING_WEBHOOKS,
    Permissions.CREATE_BOT,
    Permissions.READ_CHANNEL,
    Permissions.CREATE_POST,
    Permissions.EDIT_POST,
    Permissions.DELETE_POST,
    Permissions.MANAGE_PUBLIC_CHANNEL_PROPERTIES,
    Permissions.MANAGE_PRIVATE_CHANNEL_PROPERTIES,
    Permissions.MANAGE_PUBLIC_CHANNEL_MEMBERS,
    Permissions.MANAGE_PRIVATE_CHANNEL_MEMBERS,
    Permissions.ADD_REACTION,
    Permissions.REMOVE_REACTION,
    Permissions.UPLOAD_FILE,
    Permissions.ADD_BOOKMARK_PUBLIC_CHANNEL,
    Permissions.EDIT_BOOKMARK_PUBLIC_CHANNEL,
  ],
  [SystemRoles.SYSTEM_USER]: [
    Permissions.VIEW_TEAM,
    Permissions.CREATE_PUBLIC_CHANNEL,
    Permissions.JOIN_PUBLIC_CHANNELS,
    Permissions.READ_CHANNEL,
    Permissions.CREATE_POST,
    Permissions.EDIT_POST,
    Permissions.DELETE_POST,
    Permissions.ADD_REACTION,
    Permissions.REMOVE_REACTION,
    Permissions.UPLOAD_FILE,
  ],
  [TeamRoles.TEAM_ADMIN]: [
    Permissions.INVITE_USER,
    Permissions.ADD_USER_TO_TEAM,
    Permissions.REMOVE_USER_FROM_TEAM,
    Permissions.MANAGE_TEAM,
    Permissions.VIEW_TEAM,
    Permissions.CREATE_PUBLIC_CHANNEL,
    Permissions.CREATE_PRIVATE_CHANNEL,
    Permissions.JOIN_PUBLIC_CHANNELS,
    Permissions.MANAGE_INCOMING_WEBHOOKS,
    Permissions.MANAGE_OUTGOING_WEBHOOKS,
    Permissions.READ_CHANNEL,
    Permissions.CREATE_POST,
    Permissions.EDIT_POST,
    Permissions.DELETE_POST,
    Permissions.MANAGE_PUBLIC_CHANNEL_PROPERTIES,
    Permissions.MANAGE_PRIVATE_CHANNEL_PROPERTIES,
    Permissions.MANAGE_PUBLIC_CHANNEL_MEMBERS,
    Permissions.MANAGE_PRIVATE_CHANNEL_MEMBERS,
    Permissions.ADD_REACTION,
    Permissions.REMOVE_REACTION,
    Permissions.UPLOAD_FILE,
  ],
  [TeamRoles.TEAM_USER]: [
    Permissions.VIEW_TEAM,
    Permissions.CREATE_PUBLIC_CHANNEL,
    Permissions.JOIN_PUBLIC_CHANNELS,
    Permissions.READ_CHANNEL,
    Permissions.CREATE_POST,
    Permissions.EDIT_POST,
    Permissions.DELETE_POST,
    Permissions.ADD_REACTION,
    Permissions.REMOVE_REACTION,
    Permissions.UPLOAD_FILE,
  ],
  [ChannelRoles.CHANNEL_ADMIN]: [
    Permissions.READ_CHANNEL,
    Permissions.CREATE_POST,
    Permissions.EDIT_POST,
    Permissions.DELETE_POST,
    Permissions.MANAGE_PUBLIC_CHANNEL_PROPERTIES,
    Permissions.MANAGE_PRIVATE_CHANNEL_PROPERTIES,
    Permissions.MANAGE_PUBLIC_CHANNEL_MEMBERS,
    Permissions.MANAGE_PRIVATE_CHANNEL_MEMBERS,
    Permissions.ADD_REACTION,
    Permissions.REMOVE_REACTION,
    Permissions.UPLOAD_FILE,
    Permissions.ADD_BOOKMARK_PUBLIC_CHANNEL,
    Permissions.EDIT_BOOKMARK_PUBLIC_CHANNEL,
  ],
  [ChannelRoles.CHANNEL_USER]: [
    Permissions.READ_CHANNEL,
    Permissions.CREATE_POST,
    Permissions.EDIT_POST,
    Permissions.DELETE_POST,
    Permissions.ADD_REACTION,
    Permissions.REMOVE_REACTION,
    Permissions.UPLOAD_FILE,
  ],
} as const;